name: confwebsite2021
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  gap: ^2.0.0
  intl: ^0.17.0
  transparent_image: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  google_fonts:
  sprintf: ^6.0.0
  styled_text: ^5.1.0
  just_audio: ^0.9.20

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/photo/
    - assets/music/
