name: confwebsite2021
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  gap: ^2.0.0
  intl: ^0.17.0
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.14.0
  url_launcher: ^6.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/photo/