name: Deploy to Firebase hosting

on: pull_request

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Transpile
        run: |
          flutter build web

      - name: Deploy
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTERKAIGI }} != ''
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTERKAIGI }}"
          projectId: flutterkaigi
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
